plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

supportedArchitectures:
  cpu:
    - "current"
    - "x86"
    - "ia32"
    - "x64"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
