plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  "@aws-amplify/analytics@*":
    peerDependencies:
      react-native: "*"
  "@aws-amplify/api-graphql@*":
    dependencies:
      react-native: "*"
  "@aws-amplify/api-rest@*":
    peerDependencies:
      react-native: "*"
  "@aws-amplify/api@*":
    dependencies:
      "@aws-amplify/auth": "*"
      "@aws-amplify/cache": "*"
      "@aws-amplify/core": "*"
    peerDependencies:
      react-native: "*"
  "@aws-amplify/auth@*":
    dependencies:
      react-native: "*"
  "@aws-amplify/cache@*":
    dependencies:
      react-native: "*"
  "@aws-amplify/core@*":
    dependencies:
      react-native: "*"
  "@aws-amplify/datastore@*":
    dependencies:
      "@aws-amplify/api-graphql": "*"
      "@aws-amplify/cache": "*"
    peerDependencies:
      react-native: "*"
  "@aws-amplify/geo@*":
    peerDependencies:
      react-native: "*"
  "@aws-amplify/interactions@*":
    peerDependencies:
      react-native: "*"
  "@aws-amplify/predictions@*":
    peerDependencies:
      react-native: "*"
  "@aws-amplify/pubsub@*":
    peerDependencies:
      react-native: "*"
  "@aws-amplify/storage@*":
    dependencies:
      "@aws-sdk/protocol-http": "*"
      "@aws-sdk/querystring-builder": "*"
    peerDependencies:
      react-native: "*"
  "@aws-amplify/xr@*":
    peerDependencies:
      react-native: "*"
  "@aws-sdk/client-cloudwatch-logs@*":
    peerDependencies:
      react-native: "*"
  "@aws-sdk/client-cognito-identity@*":
    peerDependencies:
      react-native: "*"
  "@aws-sdk/client-comprehend@*":
    peerDependencies:
      react-native: "*"
  "@aws-sdk/client-firehose@*":
    peerDependencies:
      react-native: "*"
  "@aws-sdk/client-kinesis@*":
    peerDependencies:
      react-native: "*"
  "@aws-sdk/client-lex-runtime-service@*":
    peerDependencies:
      react-native: "*"
  "@aws-sdk/client-location@*":
    peerDependencies:
      react-native: "*"
  "@aws-sdk/client-personalize-events@*":
    peerDependencies:
      react-native: "*"
  "@aws-sdk/client-pinpoint@*":
    peerDependencies:
      react-native: "*"
  "@aws-sdk/client-polly@*":
    peerDependencies:
      react-native: "*"
  "@aws-sdk/client-rekognition@*":
    peerDependencies:
      react-native: "*"
  "@aws-sdk/client-s3@*":
    peerDependencies:
      react-native: "*"
  "@aws-sdk/client-sso@*":
    peerDependencies:
      react-native: "*"
  "@aws-sdk/client-sts@*":
    peerDependencies:
      react-native: "*"
  "@aws-sdk/client-textract@*":
    peerDependencies:
      react-native: "*"
  "@aws-sdk/client-translate@*":
    peerDependencies:
      react-native: "*"
  "@aws-sdk/credential-provider-cognito-identity@*":
    peerDependencies:
      react-native: "*"
  "@aws-sdk/credential-provider-ini@*":
    peerDependencies:
      react-native: "*"
  "@aws-sdk/credential-provider-node@*":
    peerDependencies:
      react-native: "*"
  "@aws-sdk/credential-provider-process@*":
    peerDependencies:
      react-native: "*"
  "@aws-sdk/credential-provider-sso@*":
    peerDependencies:
      react-native: "*"
  "@aws-sdk/middleware-retry@*":
    peerDependencies:
      react-native: "*"
  "@cspotcode/source-map-support@*":
    dependencies:
      source-map-support: "*"
  "@parcel/bundler-default@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/compressor-raw@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/namer-default@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/optimizer-cssnano@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/optimizer-htmlnano@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/optimizer-image@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/optimizer-svgo@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/optimizer-terser@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/packager-css@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/packager-html@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/packager-js@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/packager-raw@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/packager-svg@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/plugin@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/reporter-cli@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/reporter-dev-server@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/resolver-default@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/runtime-browser-hmr@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/runtime-js@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/runtime-react-refresh@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/runtime-service-worker@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/transformer-babel@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/transformer-css@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/transformer-html@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/transformer-image@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/transformer-js@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/transformer-json@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/transformer-postcss@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/transformer-posthtml@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/transformer-raw@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/transformer-react-refresh-wrap@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/transformer-svg@*":
    peerDependencies:
      "@parcel/core": "*"
  "@parcel/transformer-typescript-types@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/types@*":
    peerDependencies:
      "@parcel/core": "*"
  aws-amplify@*:
    dependencies:
      react-native: "*"
  jest@*:
    dependencies:
      "@jest/types": "*"
  react-dropzone@*:
    dependencies:
      react: "*"
  react-native-codegen@*:
    peerDependencies:
      "@babel/preset-env": "*"
  react-native@*:
    dependencies:
      "@babel/core": "*"
      "@babel/preset-env": "*"
      react: "*"

