export const fieldSizeMap: Map<string, string> = new Map([
  ['xs', 'w-14'],
  ['sm', 'w-20'],
  ['md', 'w-36'],
  ['lg', 'w-64'],
  ['xl', 'w-96'],
  ['2xl', 'w-100'],
  ['3xl', 'w-200'],
  ['full', 'w-full'],
  ['max', 'w-max'],
  ['screen', 'w-screen'],
]);

export const textColorMap: Map<string | undefined, string> = new Map([
  ['black', 'text-black'],
  ['slate', 'text-slate-600'],
  ['gray', 'text-gray-600'],
  ['zinc', 'text-zinc-600'],
  ['neutral', 'text-neutral-600'],
  ['stone', 'text-stone-600'],
  ['red', 'text-red-600'],
  ['orange', 'text-orange-600'],
  ['amber', 'text-amber-600'],
  ['yellow', 'text-yellow-600'],
  ['lime', 'text-lime-600'],
  ['green', 'text-green-600'],
  ['emerald', 'text-emerald-600'],
  ['teal', 'text-teal-600'],
  ['cyan', 'text-cyan-600'],
  ['sky', 'text-sky-600'],
  ['blue', 'text-blue-600'],
  ['indigo', 'text-indigo-600'],
  ['violet', 'text-indigo-600'],
  ['purple', 'text-purple-600'],
  ['fuchsia', 'text-fuchsia-600'],
  ['pink', 'text-pink-600'],
  ['rose', 'text-pink-600'],
  [undefined, 'text-red-900'],
]);

export const peerFocusTextColorMap: Map<string | undefined, string> = new Map([
  ['black', 'peer-focus:text-black'],
  ['slate', 'peer-focus:text-slate-600'],
  ['gray', 'peer-focus:text-gray-600'],
  ['zinc', 'peer-focus:text-zinc-600'],
  ['neutral', 'peer-focus:text-neutral-600'],
  ['stone', 'peer-focus:text-stone-600'],
  ['red', 'peer-focus:text-red-600'],
  ['orange', 'peer-focus:text-orange-600'],
  ['amber', 'peer-focus:text-amber-600'],
  ['yellow', 'peer-focus:text-yellow-600'],
  ['lime', 'peer-focus:text-lime-600'],
  ['green', 'peer-focus:text-green-600'],
  ['emerald', 'peer-focus:text-emerald-600'],
  ['teal', 'peer-focus:text-teal-600'],
  ['cyan', 'peer-focus:text-cyan-600'],
  ['sky', 'peer-focus:text-sky-600'],
  ['blue', 'peer-focus:text-blue-600'],
  ['indigo', 'peer-focus:text-indigo-600'],
  ['violet', 'peer-focus:text-indigo-600'],
  ['purple', 'peer-focus:text-purple-600'],
  ['fuchsia', 'peer-focus:text-fuchsia-600'],
  ['pink', 'peer-focus:text-pink-600'],
  ['rose', 'peer-focus:text-pink-600'],
  [undefined, 'peer-focus:text-red-900'],
]);

export const borderColorMap: Map<string | undefined, string> = new Map([
  ['black', 'border-black'],
  ['slate', 'border-slate-600'],
  ['gray', 'border-gray-600'],
  ['zinc', 'border-zinc-600'],
  ['neutral', 'border-neutral-600'],
  ['stone', 'border-stone-600'],
  ['red', 'border-red-600'],
  ['orange', 'border-orange-600'],
  ['amber', 'border-amber-600'],
  ['yellow', 'border-yellow-600'],
  ['lime', 'border-lime-600'],
  ['green', 'border-green-600'],
  ['emerald', 'border-emerald-600'],
  ['teal', 'border-teal-600'],
  ['cyan', 'border-cyan-600'],
  ['sky', 'border-sky-600'],
  ['blue', 'border-blue-600'],
  ['indigo', 'border-indigo-600'],
  ['violet', 'border-indigo-600'],
  ['purple', 'border-purple-600'],
  ['fuchsia', 'border-fuchsia-600'],
  ['pink', 'border-pink-600'],
  ['rose', 'border-pink-600'],
  [undefined, 'border-red-900'],
]);

export const focusBorderColorMap: Map<string | undefined, string> = new Map([
  ['black', 'focus:border-black'],
  ['slate', 'focus:border-slate-600'],
  ['gray', 'focus:border-gray-600'],
  ['zinc', 'focus:border-zinc-600'],
  ['neutral', 'focus:border-neutral-600'],
  ['stone', 'focus:border-stone-600'],
  ['red', 'focus:border-red-600'],
  ['orange', 'focus:border-orange-600'],
  ['amber', 'focus:border-amber-600'],
  ['yellow', 'focus:border-yellow-600'],
  ['lime', 'focus:border-lime-600'],
  ['green', 'focus:border-green-600'],
  ['emerald', 'focus:border-emerald-600'],
  ['teal', 'focus:border-teal-600'],
  ['cyan', 'focus:border-cyan-600'],
  ['sky', 'focus:border-sky-600'],
  ['blue', 'focus:border-blue-600'],
  ['indigo', 'focus:border-indigo-600'],
  ['violet', 'focus:border-indigo-600'],
  ['purple', 'focus:border-purple-600'],
  ['fuchsia', 'focus:border-fuchsia-600'],
  ['pink', 'focus:border-pink-600'],
  ['rose', 'focus:border-pink-600'],
  [undefined, 'focus:border-red-900'],
]);

export const bgColorMap: Map<string | undefined, string> = new Map([
  ['black', 'bg-black'],
  ['slate', 'bg-slate-200'],
  ['gray', 'bg-gray-200'],
  ['zinc', 'bg-zinc-200'],
  ['neutral', 'bg-neutral-200'],
  ['stone', 'bg-stone-200'],
  ['red', 'bg-red-200'],
  ['orange', 'bg-orange-200'],
  ['amber', 'bg-amber-200'],
  ['yellow', 'bg-yellow-200'],
  ['lime', 'bg-lime-200'],
  ['green', 'bg-green-200'],
  ['emerald', 'bg-emerald-200'],
  ['teal', 'bg-teal-200'],
  ['cyan', 'bg-cyan-200'],
  ['sky', 'bg-sky-200'],
  ['blue', 'bg-blue-200'],
  ['indigo', 'bg-indigo-200'],
  ['violet', 'bg-indigo-200'],
  ['purple', 'bg-purple-200'],
  ['fuchsia', 'bg-fuchsia-200'],
  ['pink', 'bg-pink-200'],
  ['rose', 'bg-pink-200'],
  [undefined, 'bg-red-200'],
]);

export const accentColorMap: Map<string | undefined, string> = new Map([
  ['black', 'accent-black'],
  ['slate', 'accent-slate-600'],
  ['gray', 'accent-gray-600'],
  ['zinc', 'accent-zinc-600'],
  ['neutral', 'accent-neutral-600'],
  ['stone', 'accent-stone-600'],
  ['red', 'accent-red-600'],
  ['orange', 'accent-orange-600'],
  ['amber', 'accent-amber-600'],
  ['yellow', 'accent-yellow-600'],
  ['lime', 'accent-lime-600'],
  ['green', 'accent-green-600'],
  ['emerald', 'accent-emerald-600'],
  ['teal', 'accent-teal-600'],
  ['cyan', 'accent-cyan-600'],
  ['sky', 'accent-sky-600'],
  ['blue', 'accent-blue-600'],
  ['indigo', 'accent-indigo-600'],
  ['violet', 'accent-indigo-600'],
  ['purple', 'accent-purple-600'],
  ['fuchsia', 'accent-fuchsia-600'],
  ['pink', 'accent-pink-600'],
  ['rose', 'accent-pink-600'],
  [undefined, 'accent-red-900'],
]);
