name: Publish

on:
  push:
    branches: 
      - 'master'
      - 'main'
      - 'beta'
      - 'next'

jobs:

  build_test_publish:
    name: Build, Test & Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 17
      uses: actions/setup-node@v2
      with:
        node-version: '17'
    
    - name: Install depedencies
      run: yarn ci
      env:
        COMPLETED_YARN_INSTALL: true

    - name: Re-install dependencies if error (fix dependabot bug)
      if: ${{ failure() }}
      run: |
        # Fix dependabot bug
        rm -f yarn.lock
        yarn install
      env:
        YARN_ENABLE_IMMUTABLE_INSTALLS: false
        COMPLETED_YARN_INSTALL: true
    
    - name: Build
      if: ${{ always() && !cancelled() && env.COMPLETED_YARN_INSTALL == 'true' }}
      run: yarn build
    
    - name: Test
      if: ${{ always() && !cancelled() && env.COMPLETED_YARN_INSTALL == 'true' }}
      run: yarn test-cov
      env: 
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN}}

    - name: Semantic Release
      if: ${{ always() && !cancelled() && env.COMPLETED_YARN_INSTALL == 'true' }}
      uses: cycjimmy/semantic-release-action@v2
      with:
        extra_plugins: |
          @semantic-release/changelog
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
