name: Test

on:
  push:
    branches: 
      - 'master'
      - 'main'
      - 'beta'
      - 'next'
  pull_request:

jobs:

  build_tes:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install depedencies
      run: yarn ci
      continue-on-error: true

    - name: Re-install dependencies if error (fix dependabot bug)
      if: ${{ failure() }}
      run: |
        # Fix dependabot bug
        rm -f yarn.lock
        yarn install
      env:
        YARN_ENABLE_IMMUTABLE_INSTALLS: false

    - name: Build package
      if: ${{ always() && !cancelled() }}
      run: yarn build

    - name: Run tests
      if: ${{ always() && !cancelled() }}
      run: yarn test
