name: Test

on:
  - pull_request

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Install dependencies (w/ dependabot bug fix)
      run: |
        # Fix dependabot bug
        rm -f yarn.lock

        yarn install

        # deduplicate lockfile
        yarn deduplicate
      env:
        YARN_ENABLE_SCRIPTS: 0 # disable postinstall scripts

    - name: Build package
      run: yarn build

    - name: Run tests
      run: yarn test
