name: Test Coveralls

on: ["push", "pull_request"]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: npm install
      run: npm install

    - name: npm install peerDependencies
      run: npm install react react-native aws-amplify

    - name: npm build
      run: npm run-script build

    - name: npm coveralls
      run: npm coveralls

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
