name: Test

on:
  push:
    branches: 
      - 'master'
      - 'main'
      - 'beta'
      - 'next'
  pull_request:

jobs:

  build_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - id: install
      name: Install depedencies
      run: |
        yarn ci
        echo "::set-output name=status::success"
      continue-on-error: true

    - name: Re-install dependencies if error (fix dependabot bug)
      if: ${{ steps.install.outputs.status != 'success' }}
      run: |
        # Fix dependabot bug
        rm -f yarn.lock
        yarn install
      env:
        YARN_ENABLE_IMMUTABLE_INSTALLS: false

    - name: Push fixed yarn.lock (fix dependabot bug)
      if: ${{ steps.install.outputs.status != 'success' }}
      run: |
        git config user.name "Github Actions"
        git config user.email actions@github.com
        git add yarn.lock
        git commit -m 'CI(Yarn): Fix yarn.lock (dependabot bug)'
        git push

    - name: Build package
      if: ${{ steps.install.outputs.status == 'success' }}
      run: yarn build

    - name: Run tests
      if: ${{ steps.install.outputs.status == 'success' }}
      run: yarn test
