name: Test Coveralls

on: ["push", "pull_request"]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: npm install + build
      run:
        npm install
        npm install react react-native aws-amplify
        npm build
        npm coveralls

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
